lint: Switch to golangci-lint
k8snetworkplumbingwg/sriov-cni pull request #210
Opened 2022-06-29 08:47 UTC by zeeke

This PR comes from [this thread on #205](https://github.com/k8snetworkplumbingwg/sriov-cni/pull/205#discussion_r908494949)

`golint` has been deprecated and this PR replaces it with `golangci-lint`, in order to have the same lint output as CI.

Also, it replace `golint` sublinter with `revive`, as suggested by [golangci-lint in its output](https://github.com/k8snetworkplumbingwg/sriov-cni/runs/7095092180?check_suite_focus=true)

```
run golangci-lint
  Running [/home/runner/golangci-lint-1.45.2-linux-amd64/golangci-lint run --out-format=github-actions --enable=golint,bodyclose,gosec,whitespace] in [] ...
  level=warning msg="[runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive."
```

2022-07-05 16:38 UTC, SchSeba commented
Thanks!
/lgtm

2022-07-12 11:30 UTC, adrianchiris requested changes
Thanks for submitting this @zeeke  !

2022-07-12 11:30 UTC, adrianchiris commented on Makefile
> +	$Q $(GOLANGCILINT) run --enable=revive,bodyclose,gosec,whitespace ./...
could we have .golangci.yml in project with linter config ? (similar to sriov dp)

then we can drop configuration here and in workflow

2022-07-15 08:33 UTC, zeeke commented
I added a minimal configuration, containing the linter list. Do you think it worths adding a full configuration like [sriov-network-operator/.golangci.yml](https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/.golangci.yml) ?

2022-07-15 09:36 UTC, eoghanlawless reviewed
+1 the minimal configuration, if we need to add anything else to it in the future, it's a trivial change.

2022-07-15 09:36 UTC, eoghanlawless commented on Makefile
> +$(GOBIN)/golangci-lint: | $(BASE) ; $(info  Installing golangci-lint...)
```suggestion
$(GOLANGCILINT): | $(BASE) ; $(info  Installing golangci-lint...)
```

2022-07-15 09:36 UTC, eoghanlawless commented on .golangci.yml
> +  enable:
```suggestion
  disable-all: true
  enable:
```

Do we need this here, it's in the network operator's `.golangci.yml`?

2022-07-17 12:35 UTC, adrianchiris approved these changes

2022-07-17 12:36 UTC, merged